unique_ids:
  assets:
    standard-page.html: NEPFVRCJPSW4ZHBMJ3654HWIYV57TBW7
    theme.css: 3DASJIYBJKWKGGHCLVY6ZAAMOTPQQLF7
  forms:
    Form1: HC3K4BAUAQ4QA3ZIQ2JWYBTRJ7VSUT6P
  modules: {}
  scripts: {}
  server_modules: {}
